### ISSUE TITLE
Hỏi đáp về DCT-64

### ISSUE THREAD

**Issue by duongs1mple** [LongClipeus/DCT-64point#2]
Em chào a , a có thể cho e thông tin liên lạc của a bên Facebook được k ạ? Em muốn hỏi anh vài thứ về project này của anh ạ. Em cảm ơn

**Comment by duongs1mple** [comment]
@LongClipeus

**Comment by LongClipeus** [comment]
@duongs1mple mình dùng sky: live:.cid.64377946fdb2742e
